import type { NextPage } from 'next'
import Head from 'next/head'
import { SectionDescription } from '../../src/components/forms/sectionDescription.component'
import { SectionTitle } from '../../src/components/forms/sectionTitle.component'
import List from '../../src/components/list'
import Heading from '../../src/components/Text/heading.component'

const InheritanceHome: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
          {/* <SideBar/> */}
          <Heading heading="Vote" children={undefined}/>
          <div className="">
            <SectionTitle title={'List of votes'}/>
            <SectionDescription desc="Disclaimer: ...."/>
          </div>
          <List/>
        </main>
  
       
      </div>
    )
  }
  
  export default InheritanceHome
  