import { useStarknetCall } from '@starknet-react/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import { SectionDescription } from '../../src/components/forms/sectionDescription.component'
import { SectionTitle } from '../../src/components/forms/sectionTitle.component'
import List from '../../src/components/list'
import VoteList from '../../src/components/list/vote'
import Heading from '../../src/components/Text/heading.component'
import { useWillContract } from '../../src/hooks/core'

const VoteHome: NextPage = () => {
  const { contract: willContract } = useWillContract();
  const { data, loading, error, refresh } = useStarknetCall({
    contract: willContract,
    method: "get_all_splits",
    args: [],
    options: { watch: false }
  })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <SideBar/> */}
        <Heading heading="Vote"><></></Heading>
        <div className="">
          <SectionTitle title={'List of votes'} />
          <SectionDescription desc="Disclaimer: ...." />
        </div>
        <List column={["No. of beneficiaries", "Beneficiaries", "Token", "Percentage (total)"]} data={data} keys={["beneficiary", "token", "expected_amount"]} />
      </main>
    </div>
  )
}

export default VoteHome
