import { useStarknetCall } from '@starknet-react/core'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { SectionDescription } from '../../src/components/forms/sectionDescription.component'
import { SectionTitle } from '../../src/components/forms/sectionTitle.component'
import List from '../../src/components/list'
import Modal from '../../src/components/modal/index.component'
import Heading from '../../src/components/Text/heading.component'
import { useWillContract } from '../../src/hooks/core'

const InheritanceHome: NextPage = () => {
    const [open, setOpen] = React.useState(false)
    const { contract: willContract } = useWillContract();
    console.log("willCOntract: ", willContract)
    const {data, loading, error, refresh} = useStarknetCall({
      contract: willContract,
      method: "get_all_splits",
      args: [],
      options: { watch: false }
    })
    function closeModal() {
      setOpen(false)
    }
  
    function openModal() {
      setOpen(true)
    }
    if (loading) return <span>Loading...</span>
    if (error) return <span>Error: {error}</span>
    return (
      <div>
        <Head>
          <title>Inheritance | Starkwill</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
        <Heading heading="Inheritance">
            <div className="mt-4 flex md:mt-0 md:ml-4">
              <button
                type="button"
                className="ml-3 inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                onClick={openModal}
              >
              + Add New
              </button>
            </div>
          </Heading>
        <Modal open={open} onClose={() => {closeModal()}}/>
        <div className="">
          <SectionTitle title={'List of inheritance'}/>
          <SectionDescription desc="Disclaimer: ...."/>
        </div>
        <List column={["No. of beneficiaries", "Beneficiaries", "Token", "Percentage (total)"]} data={data} keys={["beneficiary", "token", "expected_amount"]}/>
        {/* {
          data !== null && data !== undefined && (
          ) && console.log("data: ", data)
        } */}
        </main>
  
       
      </div>
    )
  }
  
  export default InheritanceHome
  